grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 2
model_selection:
  module_0:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      algorithm: auto
      weights: uniform
      n_neighbors: 1
    search_param_grid:
      algorithm:
      - auto
      - ball_tree
      - kd_tree
      - brute
      weights:
      - uniform
      - distance
      n_neighbors:
      - 1
      - 3
      - 5

      
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 20
      max_features: log2
      n_estimators: 100
    search_param_grid:
      max_depth:
      - 18
      - 20
      - 22
      max_features:
      - log2
      - sqrt
      n_estimators:
      - 50
      - 75
      - 100